# swap single input (prefix)

# Jason: Only take index[0] for single values
# Importance:

[[server]]
server_name = ["test.com"]
port        = ["4000"]
root        = "./website/virtualHost/2"
client_max = "10"

	[[server.location]]
	prefix          = ["/", "something"]
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["virtual_2.html"]
	autoindex       = "False"
	upload         = ["False", "OK"]
	cgi            = [""]