# Duplicate directive

# Jason: 
#	Array  -> append 
#	Single -> take the latest
# Importance: 

[[server]]
server_name = ["test.com"]
port        = ["4000", "66", "10000"]
port        = ["9000", "5000"]
root        = "./website/virtualHost/2"
root        = "abc123"
client_body = 10

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["virtual_2.html"]
	autoindex       =  false
	upload_path     =  false
	cgi_path        = [""]