# All input are string (value wrap in-between "_") 

# Jason: Inconsistence input type match
# 	port - mix str and int
#	root - must be string
#	prefix - both string and int
# Importance: 🚩

[[server]]
server_name = ["test.com"]
port        = ["4000", "5000"]
root        = "eewqweqe"
client_body = "10m"

	[[server.location]]
	prefix          = 190909
	redirect        = 50
	allowed_methods = ["GET"]
	index           = ["virtual_2.html"]
	autoindex       = "Testing..."
	upload_path     = "False"
	cgi_path        = [""]