

[[server]]
host        = "127.0.0.1"
server_name = ["test.com"]
port        = ["4000", "5000"]
root        = "./website/virtualHost/2"
client_body = "10"

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["virtual_2.html"]
	autoindex       = "Na"
	upload     = "0"
	cgi        = [".py"]


		[[server.location]]
	prefix          = "/test"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["virtual_2.html"]
	autoindex       = "Yes"
	upload     = "No"
	cgi        = [".py"]