# User_name is not part of listed directive

# Jason: Invalid directive should fail
# Importance: 🚩

[[server]]
server_name = ["test.com"]
port        = ["4000"]
root        = "./website/virtualHost/2"
client_body = 10

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["virtual_2.html"]
	autoindex       =  false
	upload_path     =  false
	cgi_path        = [""]