
[[server]]
host        = "127.0.0.1"
hdsnkfdlsnkfdlandfsklsna = ["test.com"]
port        = ["4000"]
root        = "./website/virtualHost/2"
client_body = 10

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["virtual_2.html"]
	autoindex       =  false
	upload     =  false
	cgi       = [""]