	[[server.location]]
	prefix = "/html"
	index = ["index.html", "index.htm"]   
	allowed_methods = ["GET", "HEAD", "DELETE"]
	autoindex = "on"
	redirect = "/html/success.html"
	
[[server]]
port = ["1337"]
host = "10.0.0.1  "
root = "./website/1  "  
server_name = [" hello"]
error_page = ["404 ", "/404.html"]
client_body = "10"

	[[server.location]]
	prefix = "/"  
	allowed_methods = ["GET" ,"POST", "DELETE"]
	autoindex = "on"     
	redirect = "old_about.html"
