# User_name is not part of the directive

[[server]]
host        = "127.0.0.1"
server_name = ["test.com"]
port        = ["4000"]
root        = "./website/virtualHost/2"
client_body =

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = 
	autoindex       = "False"
	upload     = "False"