# Absent directive, directly input values

[[server]]
host        = "127.0.0.1"
server_name = ["test.com"]
port        = ["4000"]
root        = "./website/virtualHost/2"
 = "10"

	[[server.location]]
	"/"
	= ""
	allowed_methods = ["GET"]
	index           = ["virtual_2.html"]
	autoindex       = "False"
	upload_path     = "False"
	cgi_path        = [""]