# items inside array without comma separating them 

[[server]]
user_name = ["test.com"]
port        = ["4000" "500"]
root        = "./website/virtualHost/2"
client_max = "10"

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["virtual_2.html"]
	autoindex       = "False"
	upload_path     = "False"
	cgi_path        = [""]