[[server]]
	server_name = ["demo.eval.com"]
	host        = "127.0.0.1"
	port        = ["4000", "8050", "21000"]
	root        = "./website/1"
	error_page  = ["403=/error/403.html  ", "404=/error/404.html  ", "500=/error/500.html"]
	client_body = "20000000"

	[[server.location]]
		prefix          = "/"
		index           = ["dashboard.html"]

	[[server.location]]
		prefix          = "/archive"
		allowed_methods = ["GET", " POST", "DELETE  "]
		autoindex       = "True"
		upload          = "True"

	[[server.location]]
		prefix          = "/youtube"
		redirect        = "https://www.youtube.com/@42berlin"

	[[server.location]]
		prefix          = "/google"
		redirect        = "https://maps.app.goo.gl/sqEeteD86CXqLisr6"
		
	[[server.location]]
		prefix          = "/internal"
		redirect        = "/hello.html"
	
	[[server.location]]
		prefix          = "/script"
		allowed_methods = ["GET", "POST"]
		cgi             = [".py", ".php", ".js"]

	[[server.location]]
		prefix          = "/dummy"
		allowed_methods = ["DELETE"]

	[[server.location]]
		prefix          = "/error"
		allowed_methods = ["GET", "POST"]
		cgi             = [".py"]

# =======================================================================

[[server]]
	server_name  = ["server_2.com"]
	host        = "127.0.0.1"
	port         = ["6900"]
	root         = "./website/2"
	client_body  = "10"

	[[server.location]]
		prefix         = "/"
		index          = ["main.html"]
		cgi		       = [".py"]

	[[server.location]]
		prefix         = "/fruit"
		index          = ["fruit.html"]

	[[server.location]]
		prefix         = "/vegetable"
		index          = ["veggies.html"]

	[[server.location]]
		prefix         = "/zombie"
		index          = ["types.html"]

	[[server.location]]
		prefix         = "/style"
		autoindex      = "True"

# =======================================================================

[[server]]
	server_name = ["server_3.com"]
	host        = "127.0.0.1"
	port        = ["9000"]
	root        = "./website/3"
	error_page  = ["404=/404.html"]
	client_body = "100000"

	[[server.location]]
		prefix          = "/"
		index           = ["main.html"]

	[[server.location]]
		prefix          = "/archive"
		allowed_methods = ["GET", "POST", "DELETE"]
		autoindex       = "True"
		upload          = "True"

# =======================================================================

[[server]]
	server_name = ["example.com"]
	host        = "127.0.0.1"
	port        = ["4000"]
	root        = "./website/virtualHost/1"
	client_body = "10"

	[[server.location]]
		prefix          = "/"
		index           = ["virtual_1.html"]

# =======================================================================

[[server]]
	host        = "127.0.0.1"
	server_name = ["test.com"]
	port        = ["4000"]
	root        = "./website/virtualHost/2"
	client_body = "10"

	[[server.location]]
		prefix          = "/"
		index           = ["virtual_2.html"]
