[[server]]
	port        = ["4000"]
	host        = "127.0.1.1  "
	root        = "./website/1  "  
	server_name = [" hello"]
	error_page  = ["404=/error/404.html"]
	client_body = "10"

	[[server.location]]
		prefix 	         = "/"  
		index            = ["dashboard.html", "index.htm"]
		allowed_methods  = ["GET" ,"POST", "DELETE"]
		autoindex        = "on"     
		upload           = "off"

	[[server.location]]
		prefix           = "/archive"
		allowed_methods  = ["GET", "HEAD", "DELETE"]
		autoindex        = "on"

	[[server.location]]   
		prefix           = "/cgi-bin"
		cgi              = [".py", ".py", ".py", ".py"]
		allowed_methods  = ["GET", "POST"]
		redirect         = "https://www.youtube.com"

# =============================================================================================

[[server]]
	port        = ["6000"]   
	host        = "  127.1.9.9  "  
	root        = "./website/2  "   
	server_name = ["example1.com", "example22.com", "example3.com"] 
	error_page  = ["404=www/error_pages/404.html"]   
	client_body = "100"

	[[server.location]]
		prefix          = "/"
		index           = ["index.html",  "index.htm"]
		allowed_methods = ["GET", "DELETE"]  
		autoindex       = "on"
		upload          = "TRUE"
