                    
					
					[[server]]

	port        = ["4000", "5555"]
	host        = "   127.0.0.1  "
	root        = " ./website/1  "  
	server_name = [" hello   "]
	error_page  = ["    404=/404.html  ", "500=/50x.html  "]
	client_body = "10000"

[[server.location]]
										prefix 	         = "/"  
										index       = ["index.html "  ,   "    index.php"]
										allowed_methods  = ["GET" ,   "POST  ", "   DELETE"]
										autoindex        = "on"
										cgi         = [" .mtm"]

		upload           = "OFF  "
		redirect         = "  https://www.youtube.com/ "

[[server.location]]
		prefix           = "/html"
		allowed_methods  = ["GET", "HEAD", "DELETE"]  

		index = ["nice.py"]

		autoindex        = "TRue"
		redirect         = "/html/success.html"
