[[server]]
host        = "127.0.0.1"
server_name = ["demo.eval.com"]
port        = ["4000", "8050", "21000"]
root        = "./website/1"
error_page  = ["403=/error/403.html  ", "404=/error/404.html  ", "500=/error/500.html  "]
client_body = "20000000"

# ====================================================================

[[server]]
host        = "127.0.0.1"
server_name  = ["server_2.com"]
port         = ["6900"]
root         = "./website/2"
client_body  = "10"

# =======================================================================

[[server]]
host        = "127.0.0.1"
server_name = ["server_3.com"]
port        = ["9000"]
root        = "./website/3"
error_page  = ["404=/404.html"]
client_body = "100000"
