[[server]]
host        = "127.0.0.1"
#server_name = ["demo.eval.com"]
port        = ["4000", "8050", "21000"]
root        = "./website/1"
error_page  = ["403=/error/403.html  ", "404=/error/404.html  ", "500=/error/500.html  "]
client_body = "20000000"

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["dashboard.html"]
	autoindex       = "False"
	upload          = "False"
	cgi             = [""]

# ====================================================================

[[server]]
host        = "127.0.0.1"
server_name = ["example.com"]
port        = ["4000"]
root        = "./website/virtualHost/1"
client_body = "10"

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["virtual_1.html"]
	autoindex       = "False"
	upload          = "False"
	cgi             = [""]

# =====================================================================

[[server]]
host        = "127.0.0.1"
server_name = ["test.com"]
port        = ["4000"]
root        = "./website/virtualHost/2"
client_body = "10"

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["virtual_2.html"]
	autoindex       = "False"
	upload          = "False"
	cgi             = [""]
