[[server]]
host        = "127.0.0.1"
server_name = ["demo.eval.com"]
port        = ["4000", "8050", "21000"]
root        = "./website/1"
error_page  = ["403=/error/403.html  ", "404=/error/404.html  ", "500=/error/500.html  "]
client_body = "20000000"

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["dashboard.html"]
	autoindex       = "False"
	upload          = "False"

	[[server.location]]
	prefix          = "/archive"
	redirect        = ""
	allowed_methods = ["GET", " POST", "DELETE  "]
	index           = [""]
	autoindex       = "True"
	upload          = "True"

	[[server.location]]
	prefix          = "/youtube"
	redirect        = "https://www.youtube.com/@42berlin"
	allowed_methods = ["GET"]
	index           = [""]
	autoindex       = "False"
	upload          = "False"

	[[server.location]]
	prefix          = "/google"
	redirect        = "https://maps.app.goo.gl/sqEeteD86CXqLisr6"
	allowed_methods = ["GET"]
	index           = [""]
	autoindex       = "False"
	upload          = "False"

	[[server.location]]
	prefix          = "/internal"
	redirect        = "/hello.html"
	allowed_methods = ["GET"]
	index           = [""]
	autoindex       = "False"
	upload          = "False"

	[[server.location]]
	prefix          = "/script"
	redirect        = ""
	allowed_methods = ["GET", "POST"]
	index           = [""]
	autoindex       = "False"
	upload          = "False"
	cgi            = [".py", ".php", ".js"]

	[[server.location]]
	prefix          = "/dummy"
	redirect        = ""
	allowed_methods = ["DELETE"]
	index           = [""]
	autoindex       = "False"
	upload          = "False"

	[[server.location]]
	prefix          = "/error"
	redirect        = ""
	allowed_methods = ["GET", "POST"]
	index           = [""]
	autoindex       = "False"
	upload          = "False"
	cgi             = [".py"]

# ====================================================================

[[server]]
host        = "127.0.0.1"
server_name  = ["server_2.com"]
port         = ["6900"]
root         = "./website/2"
client_body  = "10"

	[[server.location]]
	prefix           = "/"
	redirect         = ""
	allowed_methods  = ["GET"]
	index            = ["main.html"]
	autoindex        = "False"
	upload           = "False"
	cgi             = [".py"]

	[[server.location]]
	prefix          = "/fruit"
	redirect        = ""
	allowed_methods = ["GET"]
	index            = ["fruit.html"]
	autoindex       = "False"
	upload          = "False"

	[[server.location]]
	prefix          = "/vegetable"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["veggies.html"]
	autoindex       = "False"
	upload          = "False"

	[[server.location]]
	prefix          = "/zombie"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["types.html"]
	autoindex       = "False"
	upload          = "False"

	[[server.location]]
	prefix          = "/style"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = [""]
	autoindex       = "True"
	upload          = "False"

# =======================================================================

[[server]]
host        = "127.0.0.1"
server_name = ["server_3.com"]
port        = ["9000"]
root        = "./website/3"
error_page  = ["404=/404.html"]
client_body = "100000"

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["main.html"]
	autoindex       = "False"
	upload          = "False"

	[[server.location]]
	prefix          = "/archive"
	redirect        = ""
	allowed_methods = ["GET", "POST", "DELETE"]
	index           = [""]
	autoindex       = "True"
	upload          = "True"

# ====================================================================

[[server]]
host        = "127.0.0.1"
server_name = ["example.com"]
port        = ["4000"]
root        = "./website/virtualHost/1"
client_body = "10"

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["virtual_1.html"]
	autoindex       = "False"
	upload          = "False"

# =====================================================================

[[server]]
host        = "127.0.0.1"
server_name = ["test.com"]
port        = ["4000"]
root        = "./website/virtualHost/2"
client_body = "10"

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["virtual_2.html"]
	autoindex       = "False"
	upload          = "False"
