[[server]]
host        = "127.0.0.1"
server_name = ["demo.eval.com"]
port        = ["4000", "8050", "21000"]
root        = "./website/1"
error_page  = ["403=/error/403.html  ", "404=/invalid/404.html", "500=/error/500.html"]
client_body = "20000000"

	[[server.location]]
	prefix          = "/"
	redirect        = ""
	allowed_methods = ["GET"]
	index           = ["dashboard.html"]
	autoindex       = "False"
	upload          = "False"

	[[server.location]]
	prefix          = "/archive/subfolder/deepNest"
	allowed_methods = ["GET", " POST", "DELETE  "]
	autoindex       = "True"
	upload          = "True"

	[[server.location]]
	prefix          = "/archive/subfolder"
	allowed_methods = ["GET"]
	index           = ["netPractice.json"]